### ISSUE TITLE
Bugs...

### ISSUE THREAD

**Issue by lukasyelle** [ritstudentgovernment/PawPrints-Archive#137]
Clicking on a link to a petition (or refreshing a page that a petition is open on) no longer re-opens the petition modal (what the "p" query param is for).
- That means sharing petitions is impossible at the moment

### Petition search:
- Searching for any text always returns no results
- You can no longer filter on status for some reason?

### Cross-browser compatibility:
- Progress bars are messed up (size + color) on Safari
- The Petition Timeline is reversed on Firefox

### Nav Bar:
- When you scroll down the navigation bar gets bigger now instead of smaller
- On the Profile page the nav links are black instead of white like on the other pages

The page title is broken on the Committees page

**Comment by Jack-Papel-RIT** [comment]
Also, when the navbar is expanded, the dropdown on "Hi there, {name}" is misplaced, making it very difficult to use,

**Comment by Jack-Papel-RIT** [comment]
For the petition text search, it appears that the search isn't broken - rather that the loading message is "No petitions fit that query!". If you wait a couple seconds, the results show up. But, this misleading message should also be fixed.

**Comment by MoralCode** [comment]
> Clicking on a link to a petition (or refreshing a page that a petition is open on) no longer re-opens the petition modal (what the "p" query param is for).

This seems to work now. is this still an issue for you?



> Searching for any text always returns no results

This is a known issue relating to the performance of the database. The results will show up eventually, they just take a while longer than most people expect and aren't well cached.  

> The Petition Timeline is reversed on Firefox

I dont see this issue as a firefox user. Is this still a problem for you?

> When you scroll down the navigation bar gets bigger now instead of smaller

Yeah i see that too... weird

> The page title is broken on the Committees page

Not sure what you mean by this. Do you have a screenshot/is this still an issue for you? Does this also affect the about page?

**Comment by Jack-Papel** [comment]
The "page title" refers to the text in the tab name

**Comment by MoralCode** [comment]
Post for status updates/checking off the items:

- [X] Clicking on a link to a petition (or refreshing a page that a petition is open on) no longer re-opens the petition modal (what the "p" query param is for). That means sharing petitions is impossible at the moment [ cannot reproduce]

- [X] Search has misleading loading message [moved to #161 ]

- [ ] You can no longer filter on status for some reason? [  the SG tech services team will probably know why]

- [x] Progress bars are messed up (size + color) on Safari #172

- [X] The Petition Timeline is reversed on Firefox [ see more specific issue for this #155]

- [X] When you scroll down the navigation bar gets bigger now instead of smaller #152 

- [x] On the Profile page the nav links are black instead of white like on the other pages [ already covered by a more specific issue #144 - redirect all conversation there]

- [X] The page `<title>` is broken on the Committees page [fixed when #154 gets merged ]

**Comment by MoralCode** [comment]
tried to confirm the "petition modal not opening" issue on librewolf (linux) and brave (linux) and macOS safari (through a friend) and could not reproduce the issue.


the only other remaining issue from this list of bugs is " You can no longer filter on status for some reason?", which may be a question for the SG tech services team.

other than that every issue has either been resolved or moved to a separate issue

**Comment by Sma-Das** [comment]
> tried to confirm the "petition modal not opening" issue on librewolf (linux) and brave (linux) and macOS safari (through a friend) and could not reproduce the issue.
> 
> 
> the only other remaining issue from this list of bugs is " You can no longer filter on status for some reason?", which may be a question for the SG tech services team.
> 
> other than that every issue has either been resolved or moved to a separate issue

I've seen this issue and it's often a result of extensions interfering with page loading etc.

**Comment by MoralCode** [comment]
> I've seen this issue and it's often a result of extensions interfering with page loading etc.

So the petition modal not loading is being classified as user error?
